// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: languages.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkLangCodeExists = `-- name: CheckLangCodeExists :one
SELECT EXISTS (
    SELECT 1
    FROM languages
    WHERE lang_code = $1
  ) as exists
`

func (q *Queries) CheckLangCodeExists(ctx context.Context, langCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkLangCodeExists, langCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkLanguageExists = `-- name: CheckLanguageExists :one
SELECT EXISTS (
    SELECT 1
    FROM languages
    WHERE id = $1
  ) as exists
`

func (q *Queries) CheckLanguageExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkLanguageExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkNameExists = `-- name: CheckNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM languages
    WHERE name = $1
  ) as exists
`

func (q *Queries) CheckNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countLanguages = `-- name: CountLanguages :one
SELECT COUNT(*) as total
FROM languages
`

func (q *Queries) CountLanguages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLanguages)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages(id, name, lang_code)
VALUES($1, $2, $3)
RETURNING id, name, lang_code, created_at, updated_at
`

type CreateLanguageParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	LangCode string    `json:"lang_code"`
}

func (q *Queries) CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error) {
	row := q.db.QueryRowContext(ctx, createLanguage, arg.ID, arg.Name, arg.LangCode)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LangCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLanguage = `-- name: DeleteLanguage :exec
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLanguage, id)
	return err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLanguage(ctx context.Context, id uuid.UUID) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguage, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LangCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByLangCode = `-- name: GetLanguageByLangCode :one
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE lang_code = $1
LIMIT 1
`

func (q *Queries) GetLanguageByLangCode(ctx context.Context, langCode string) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguageByLangCode, langCode)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LangCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguageByName = `-- name: GetLanguageByName :one
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetLanguageByName(ctx context.Context, name string) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguageByName, name)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LangCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLanguagesCursorFirst = `-- name: GetLanguagesCursorFirst :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetLanguagesCursorFirst(ctx context.Context, limit int32) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, getLanguagesCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLanguagesPaginated = `-- name: GetLanguagesPaginated :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetLanguagesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLanguagesPaginated(ctx context.Context, arg GetLanguagesPaginatedParams) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, getLanguagesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLanguages = `-- name: SearchLanguages :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE (
    name ILIKE '%' || $1 || '%'
    OR lang_code ILIKE '%' || $1 || '%'
  )
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    WHEN lang_code ILIKE $1 || '%' THEN 2
    ELSE 3
  END,
  created_at DESC
`

func (q *Queries) SearchLanguages(ctx context.Context, dollar_1 sql.NullString) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, searchLanguages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLanguagesByLangCode = `-- name: SearchLanguagesByLangCode :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE lang_code ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN lang_code ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  lang_code ASC
`

func (q *Queries) SearchLanguagesByLangCode(ctx context.Context, dollar_1 sql.NullString) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, searchLanguagesByLangCode, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLanguagesByName = `-- name: SearchLanguagesByName :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  name ASC
`

func (q *Queries) SearchLanguagesByName(ctx context.Context, dollar_1 sql.NullString) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, searchLanguagesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLanguagesPaginated = `-- name: SearchLanguagesPaginated :many
SELECT id, name, lang_code, created_at, updated_at
FROM languages
WHERE (
    name ILIKE '%' || $1 || '%'
    OR lang_code ILIKE '%' || $1 || '%'
  )
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    WHEN lang_code ILIKE $1 || '%' THEN 2
    ELSE 3
  END,
  created_at DESC
LIMIT $2 OFFSET $3
`

type SearchLanguagesPaginatedParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchLanguagesPaginated(ctx context.Context, arg SearchLanguagesPaginatedParams) ([]Language, error) {
	rows, err := q.db.QueryContext(ctx, searchLanguagesPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LangCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguage = `-- name: UpdateLanguage :one
UPDATE languages
SET name = COALESCE($2, name),
  lang_code = COALESCE($3, lang_code)
WHERE id = $1
RETURNING id, name, lang_code, created_at, updated_at
`

type UpdateLanguageParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	LangCode string    `json:"lang_code"`
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error) {
	row := q.db.QueryRowContext(ctx, updateLanguage, arg.ID, arg.Name, arg.LangCode)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LangCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
