// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	IDCategory   uuid.UUID      `json:"id_category"`
	Description  sql.NullString `json:"description"`
	IsDeployed   bool           `json:"is_deployed"`
	IsMaintained bool           `json:"is_maintained"`
	LiveDemo     sql.NullString `json:"live_demo"`
	SourceCode   sql.NullString `json:"source_code"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ProjectImage struct {
	ID        uuid.UUID    `json:"id"`
	IDProject uuid.UUID    `json:"id_project"`
	FileName  string       `json:"file_name"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Tech struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LogoUrl     sql.NullString `json:"logo_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type TechStack struct {
	IDProject uuid.UUID    `json:"id_project"`
	IDTech    uuid.UUID    `json:"id_tech"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Address   sql.NullString `json:"address"`
	FullName  sql.NullString `json:"full_name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type UserTranslation struct {
	ID               uuid.UUID      `json:"id"`
	IDUser           uuid.UUID      `json:"id_user"`
	Bio              sql.NullString `json:"bio"`
	AboutMe          sql.NullString `json:"about_me"`
	AdditionalSkills []string       `json:"additional_skills"`
	Languages        []string       `json:"languages"`
	Quote            sql.NullString `json:"quote"`
	LangCode         string         `json:"lang_code"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}
