// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Language struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	LangCode  string       `json:"lang_code"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID      `json:"id"`
	IDUser       uuid.UUID      `json:"id_user"`
	IDCategory   uuid.UUID      `json:"id_category"`
	IsDeployed   bool           `json:"is_deployed"`
	IsMaintained bool           `json:"is_maintained"`
	LiveDemo     sql.NullString `json:"live_demo"`
	SourceCode   sql.NullString `json:"source_code"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ProjectImage struct {
	ID        uuid.UUID    `json:"id"`
	IDProject uuid.UUID    `json:"id_project"`
	FileName  string       `json:"file_name"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ProjectTranslation struct {
	ID          uuid.UUID      `json:"id"`
	IDProject   uuid.UUID      `json:"id_project"`
	IDLanguage  uuid.UUID      `json:"id_language"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Tech struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LogoUrl     sql.NullString `json:"logo_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type TechStack struct {
	IDProject uuid.UUID    `json:"id_project"`
	IDTech    uuid.UUID    `json:"id_tech"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Password   string         `json:"password"`
	Role       UserRole       `json:"role"`
	Address    sql.NullString `json:"address"`
	FullName   sql.NullString `json:"full_name"`
	IDLanguage uuid.NullUUID  `json:"id_language"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type UserTranslation struct {
	ID               uuid.UUID      `json:"id"`
	IDUser           uuid.UUID      `json:"id_user"`
	IDLanguage       uuid.UUID      `json:"id_language"`
	Bio              sql.NullString `json:"bio"`
	AboutMe          sql.NullString `json:"about_me"`
	AdditionalSkills []string       `json:"additional_skills"`
	Languages        []string       `json:"languages"`
	Quote            sql.NullString `json:"quote"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}
