// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_images.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const checkProjectImageExists = `-- name: CheckProjectImageExists :one
SELECT EXISTS (
    SELECT 1
    FROM project_images
    WHERE id = $1
  ) as exists
`

func (q *Queries) CheckProjectImageExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectImageExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProjectImages = `-- name: CountProjectImages :one
SELECT COUNT(*) as total
FROM project_images
`

func (q *Queries) CountProjectImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectImages)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProjectImage = `-- name: CreateProjectImage :one
INSERT INTO project_images (id, id_project, file_name, url)
VALUES ($1, $2, $3, $4)
RETURNING id, id_project, file_name, url, created_at, updated_at
`

type CreateProjectImageParams struct {
	ID        uuid.UUID `json:"id"`
	IDProject uuid.UUID `json:"id_project"`
	FileName  string    `json:"file_name"`
	Url       string    `json:"url"`
}

func (q *Queries) CreateProjectImage(ctx context.Context, arg CreateProjectImageParams) (ProjectImage, error) {
	row := q.db.QueryRowContext(ctx, createProjectImage,
		arg.ID,
		arg.IDProject,
		arg.FileName,
		arg.Url,
	)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.FileName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectImagesBatch = `-- name: CreateProjectImagesBatch :many
INSERT INTO project_images (id, id_project, file_name, url)
SELECT (item->>'id')::uuid,
  (item->>'id_project')::uuid,
  item->>'file_name',
  item->>'url'
FROM json_array_elements($1::json) AS item
RETURNING id, id_project, file_name, url, created_at, updated_at
`

func (q *Queries) CreateProjectImagesBatch(ctx context.Context, dollar_1 json.RawMessage) ([]ProjectImage, error) {
	rows, err := q.db.QueryContext(ctx, createProjectImagesBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.FileName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProjectImage = `-- name: DeleteProjectImage :exec
DELETE FROM project_images
WHERE id = $1
`

func (q *Queries) DeleteProjectImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectImage, id)
	return err
}

const getProjectImage = `-- name: GetProjectImage :one
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectImage(ctx context.Context, id uuid.UUID) (ProjectImage, error) {
	row := q.db.QueryRowContext(ctx, getProjectImage, id)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.FileName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectImageByName = `-- name: GetProjectImageByName :one
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
WHERE file_name = $1
LIMIT 1
`

func (q *Queries) GetProjectImageByName(ctx context.Context, fileName string) (ProjectImage, error) {
	row := q.db.QueryRowContext(ctx, getProjectImageByName, fileName)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.FileName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectImagesCursorFirst = `-- name: GetProjectImagesCursorFirst :many
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetProjectImagesCursorFirst(ctx context.Context, limit int32) ([]ProjectImage, error) {
	rows, err := q.db.QueryContext(ctx, getProjectImagesCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.FileName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectImagesPaginated = `-- name: GetProjectImagesPaginated :many
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetProjectImagesPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetProjectImagesPaginated(ctx context.Context, arg GetProjectImagesPaginatedParams) ([]ProjectImage, error) {
	rows, err := q.db.QueryContext(ctx, getProjectImagesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.FileName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectImages = `-- name: SearchProjectImages :many
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
`

func (q *Queries) SearchProjectImages(ctx context.Context, dollar_1 sql.NullString) ([]ProjectImage, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectImages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.FileName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectImagesPaginated = `-- name: SearchProjectImagesPaginated :many
SELECT id, id_project, file_name, url, created_at, updated_at
FROM project_images
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProjectImagesPaginatedParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchProjectImagesPaginated(ctx context.Context, arg SearchProjectImagesPaginatedParams) ([]ProjectImage, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectImagesPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.FileName,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectImage = `-- name: UpdateProjectImage :one
UPDATE project_images
SET file_name = COALESCE($2, file_name),
  url = COALESCE($3, url)
WHERE id = $1
RETURNING id, id_project, file_name, url, created_at, updated_at
`

type UpdateProjectImageParams struct {
	ID       uuid.UUID `json:"id"`
	FileName string    `json:"file_name"`
	Url      string    `json:"url"`
}

func (q *Queries) UpdateProjectImage(ctx context.Context, arg UpdateProjectImageParams) (ProjectImage, error) {
	row := q.db.QueryRowContext(ctx, updateProjectImage, arg.ID, arg.FileName, arg.Url)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.FileName,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
