// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const checkProjectExists = `-- name: CheckProjectExists :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE id = $1
  )
`

func (q *Queries) CheckProjectExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)
FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    id_user,
    id_category,
    is_deployed,
    is_maintained,
    live_demo,
    source_code
  )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, id_user, id_category, is_deployed, is_maintained, live_demo, source_code, created_at, updated_at
`

type CreateProjectParams struct {
	ID           uuid.UUID      `json:"id"`
	IDUser       uuid.UUID      `json:"id_user"`
	IDCategory   uuid.UUID      `json:"id_category"`
	IsDeployed   bool           `json:"is_deployed"`
	IsMaintained bool           `json:"is_maintained"`
	LiveDemo     sql.NullString `json:"live_demo"`
	SourceCode   sql.NullString `json:"source_code"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.IDUser,
		arg.IDCategory,
		arg.IsDeployed,
		arg.IsMaintained,
		arg.LiveDemo,
		arg.SourceCode,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCategory,
		&i.IsDeployed,
		&i.IsMaintained,
		&i.LiveDemo,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT p.id,
  p.id_user,
  p.id_category,
  p.is_deployed,
  p.is_maintained,
  p.live_demo,
  p.source_code,
  p.created_at,
  p.updated_at,
  json_build_object(
    'id',
    u.id,
    'username',
    u.username,
    'email',
    u.email
  ) as user,
  json_build_object(
    'id',
    c.id,
    'name',
    c.name,
    'description',
    c.description
  ) as category,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pt.id,
            'id_language',
            pt.id_language,
            'name',
            pt.name,
            'description',
            pt.description,
            'language',
            json_build_object(
              'id',
              l.id,
              'code',
              l.code,
              'name',
              l.name
            )
          )
          ORDER BY l.name
        ),
        '[]'::json
      )
    FROM project_translations pt
      JOIN languages l ON pt.id_language = l.id
    WHERE pt.id_project = p.id
  ) as translations,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            t.id,
            'name',
            t.name,
            'description',
            t.description,
            'logo_url',
            t.logo_url
          )
          ORDER BY t.name
        ),
        '[]'::json
      )
    FROM tech_stacks ts
      JOIN techs t ON ts.id_tech = t.id
    WHERE ts.id_project = p.id
  ) as techs,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pi.id,
            'file_name',
            pi.file_name,
            'url',
            pi.url
          )
          ORDER BY pi.created_at
        ),
        '[]'::json
      )
    FROM project_images pi
    WHERE pi.id_project = p.id
  ) as images
FROM projects p
  JOIN users u ON p.id_user = u.id
  JOIN categories c ON p.id_category = c.id
WHERE p.id = $1
LIMIT 1
`

type GetProjectRow struct {
	ID           uuid.UUID       `json:"id"`
	IDUser       uuid.UUID       `json:"id_user"`
	IDCategory   uuid.UUID       `json:"id_category"`
	IsDeployed   bool            `json:"is_deployed"`
	IsMaintained bool            `json:"is_maintained"`
	LiveDemo     sql.NullString  `json:"live_demo"`
	SourceCode   sql.NullString  `json:"source_code"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	User         json.RawMessage `json:"user"`
	Category     json.RawMessage `json:"category"`
	Translations interface{}     `json:"translations"`
	Techs        interface{}     `json:"techs"`
	Images       interface{}     `json:"images"`
}

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (GetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCategory,
		&i.IsDeployed,
		&i.IsMaintained,
		&i.LiveDemo,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Category,
		&i.Translations,
		&i.Techs,
		&i.Images,
	)
	return i, err
}

const getProjectByTranslatedName = `-- name: GetProjectByTranslatedName :one
SELECT p.id,
  p.id_user,
  p.id_category,
  p.is_deployed,
  p.is_maintained,
  p.live_demo,
  p.source_code,
  p.created_at,
  p.updated_at,
  json_build_object(
    'id',
    u.id,
    'username',
    u.username,
    'email',
    u.email
  ) as user,
  json_build_object(
    'id',
    c.id,
    'name',
    c.name,
    'description',
    c.description
  ) as category,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pt_agg.id,
            'id_language',
            pt_agg.id_language,
            'name',
            pt_agg.name,
            'description',
            pt_agg.description,
            'language',
            json_build_object(
              'id',
              l.id,
              'code',
              l.code,
              'name',
              l.name
            )
          )
          ORDER BY l.name
        ),
        '[]'::json
      )
    FROM project_translations pt_agg
      JOIN languages l ON pt_agg.id_language = l.id
    WHERE pt_agg.id_project = p.id
  ) as translations,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            t.id,
            'name',
            t.name,
            'description',
            t.description,
            'logo_url',
            t.logo_url
          )
          ORDER BY t.name
        ),
        '[]'::json
      )
    FROM tech_stacks ts
      JOIN techs t ON ts.id_tech = t.id
    WHERE ts.id_project = p.id
  ) as techs,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pi.id,
            'file_name',
            pi.file_name,
            'url',
            pi.url
          )
          ORDER BY pi.created_at
        ),
        '[]'::json
      )
    FROM project_images pi
    WHERE pi.id_project = p.id
  ) as images
FROM projects p
  JOIN users u ON p.id_user = u.id
  JOIN categories c ON p.id_category = c.id
  JOIN project_translations pt ON p.id = pt.id_project
WHERE pt.name = $1
LIMIT 1
`

type GetProjectByTranslatedNameRow struct {
	ID           uuid.UUID       `json:"id"`
	IDUser       uuid.UUID       `json:"id_user"`
	IDCategory   uuid.UUID       `json:"id_category"`
	IsDeployed   bool            `json:"is_deployed"`
	IsMaintained bool            `json:"is_maintained"`
	LiveDemo     sql.NullString  `json:"live_demo"`
	SourceCode   sql.NullString  `json:"source_code"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	User         json.RawMessage `json:"user"`
	Category     json.RawMessage `json:"category"`
	Translations interface{}     `json:"translations"`
	Techs        interface{}     `json:"techs"`
	Images       interface{}     `json:"images"`
}

func (q *Queries) GetProjectByTranslatedName(ctx context.Context, name string) (GetProjectByTranslatedNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectByTranslatedName, name)
	var i GetProjectByTranslatedNameRow
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCategory,
		&i.IsDeployed,
		&i.IsMaintained,
		&i.LiveDemo,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User,
		&i.Category,
		&i.Translations,
		&i.Techs,
		&i.Images,
	)
	return i, err
}

const getProjectsCursorFirst = `-- name: GetProjectsCursorFirst :many
SELECT p.id,
  p.id_user,
  p.id_category,
  p.is_deployed,
  p.is_maintained,
  p.live_demo,
  p.source_code,
  p.created_at,
  p.updated_at,
  json_build_object(
    'id',
    u.id,
    'username',
    u.username,
    'email',
    u.email
  ) as user,
  json_build_object(
    'id',
    c.id,
    'name',
    c.name,
    'description',
    c.description
  ) as category,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pt.id,
            'id_language',
            pt.id_language,
            'name',
            pt.name,
            'description',
            pt.description,
            'language',
            json_build_object(
              'id',
              l.id,
              'code',
              l.code,
              'name',
              l.name
            )
          )
          ORDER BY l.name
        ),
        '[]'::json
      )
    FROM project_translations pt
      JOIN languages l ON pt.id_language = l.id
    WHERE pt.id_project = p.id
  ) as translations,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            t.id,
            'name',
            t.name,
            'description',
            t.description,
            'logo_url',
            t.logo_url
          )
          ORDER BY t.name
        ),
        '[]'::json
      )
    FROM tech_stacks ts
      JOIN techs t ON ts.id_tech = t.id
    WHERE ts.id_project = p.id
  ) as techs,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pi.id,
            'file_name',
            pi.file_name,
            'url',
            pi.url
          )
          ORDER BY pi.created_at
        ),
        '[]'::json
      )
    FROM project_images pi
    WHERE pi.id_project = p.id
  ) as images
FROM projects p
  JOIN users u ON p.id_user = u.id
  JOIN categories c ON p.id_category = c.id
ORDER BY p.created_at DESC
LIMIT $1
`

type GetProjectsCursorFirstRow struct {
	ID           uuid.UUID       `json:"id"`
	IDUser       uuid.UUID       `json:"id_user"`
	IDCategory   uuid.UUID       `json:"id_category"`
	IsDeployed   bool            `json:"is_deployed"`
	IsMaintained bool            `json:"is_maintained"`
	LiveDemo     sql.NullString  `json:"live_demo"`
	SourceCode   sql.NullString  `json:"source_code"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	User         json.RawMessage `json:"user"`
	Category     json.RawMessage `json:"category"`
	Translations interface{}     `json:"translations"`
	Techs        interface{}     `json:"techs"`
	Images       interface{}     `json:"images"`
}

func (q *Queries) GetProjectsCursorFirst(ctx context.Context, limit int32) ([]GetProjectsCursorFirstRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectsCursorFirstRow{}
	for rows.Next() {
		var i GetProjectsCursorFirstRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDCategory,
			&i.IsDeployed,
			&i.IsMaintained,
			&i.LiveDemo,
			&i.SourceCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
			&i.Category,
			&i.Translations,
			&i.Techs,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsPaginated = `-- name: GetProjectsPaginated :many
SELECT p.id,
  p.id_user,
  p.id_category,
  p.is_deployed,
  p.is_maintained,
  p.live_demo,
  p.source_code,
  p.created_at,
  p.updated_at,
  json_build_object(
    'id',
    u.id,
    'username',
    u.username,
    'email',
    u.email
  ) as user,
  json_build_object(
    'id',
    c.id,
    'name',
    c.name,
    'description',
    c.description
  ) as category,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pt.id,
            'id_language',
            pt.id_language,
            'name',
            pt.name,
            'description',
            pt.description,
            'language',
            json_build_object(
              'id',
              l.id,
              'code',
              l.code,
              'name',
              l.name
            )
          )
          ORDER BY l.name
        ),
        '[]'::json
      )
    FROM project_translations pt
      JOIN languages l ON pt.id_language = l.id
    WHERE pt.id_project = p.id
  ) as translations,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            t.id,
            'name',
            t.name,
            'description',
            t.description,
            'logo_url',
            t.logo_url
          )
          ORDER BY t.name
        ),
        '[]'::json
      )
    FROM tech_stacks ts
      JOIN techs t ON ts.id_tech = t.id
    WHERE ts.id_project = p.id
  ) as techs,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pi.id,
            'file_name',
            pi.file_name,
            'url',
            pi.url
          )
          ORDER BY pi.created_at
        ),
        '[]'::json
      )
    FROM project_images pi
    WHERE pi.id_project = p.id
  ) as images
FROM projects p
  JOIN users u ON p.id_user = u.id
  JOIN categories c ON p.id_category = c.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetProjectsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetProjectsPaginatedRow struct {
	ID           uuid.UUID       `json:"id"`
	IDUser       uuid.UUID       `json:"id_user"`
	IDCategory   uuid.UUID       `json:"id_category"`
	IsDeployed   bool            `json:"is_deployed"`
	IsMaintained bool            `json:"is_maintained"`
	LiveDemo     sql.NullString  `json:"live_demo"`
	SourceCode   sql.NullString  `json:"source_code"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	User         json.RawMessage `json:"user"`
	Category     json.RawMessage `json:"category"`
	Translations interface{}     `json:"translations"`
	Techs        interface{}     `json:"techs"`
	Images       interface{}     `json:"images"`
}

func (q *Queries) GetProjectsPaginated(ctx context.Context, arg GetProjectsPaginatedParams) ([]GetProjectsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectsPaginatedRow{}
	for rows.Next() {
		var i GetProjectsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDCategory,
			&i.IsDeployed,
			&i.IsMaintained,
			&i.LiveDemo,
			&i.SourceCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
			&i.Category,
			&i.Translations,
			&i.Techs,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectsPaginated = `-- name: SearchProjectsPaginated :many
WITH relevant_projects AS (
  SELECT DISTINCT ON (p.id) p.id,
    pt.name as matched_name,
    p.created_at
  FROM projects p
    JOIN project_translations pt ON p.id = pt.id_project
  WHERE pt.name ILIKE '%' || $1::text || '%'
)
SELECT p.id,
  p.id_user,
  p.id_category,
  p.is_deployed,
  p.is_maintained,
  p.live_demo,
  p.source_code,
  p.created_at,
  p.updated_at,
  json_build_object(
    'id',
    u.id,
    'username',
    u.username,
    'email',
    u.email
  ) as user,
  json_build_object(
    'id',
    c.id,
    'name',
    c.name,
    'description',
    c.description
  ) as category,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pt.id,
            'id_language',
            pt.id_language,
            'name',
            pt.name,
            'description',
            pt.description,
            'language',
            json_build_object(
              'id',
              l.id,
              'code',
              l.code,
              'name',
              l.name
            )
          )
          ORDER BY l.name
        ),
        '[]'::json
      )
    FROM project_translations pt
      JOIN languages l ON pt.id_language = l.id
    WHERE pt.id_project = p.id
  ) as translations,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            t.id,
            'name',
            t.name,
            'description',
            t.description,
            'logo_url',
            t.logo_url
          )
          ORDER BY t.name
        ),
        '[]'::json
      )
    FROM tech_stacks ts
      JOIN techs t ON ts.id_tech = t.id
    WHERE ts.id_project = p.id
  ) as techs,
  (
    SELECT COALESCE(
        json_agg(
          json_build_object(
            'id',
            pi.id,
            'file_name',
            pi.file_name,
            'url',
            pi.url
          )
          ORDER BY pi.created_at
        ),
        '[]'::json
      )
    FROM project_images pi
    WHERE pi.id_project = p.id
  ) as images
FROM projects p
  JOIN users u ON p.id_user = u.id
  JOIN categories c ON p.id_category = c.id
  JOIN relevant_projects rp ON p.id = rp.id
ORDER BY CASE
    WHEN rp.matched_name ILIKE $1::text || '%' THEN 1
    ELSE 2
  END,
  rp.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProjectsPaginatedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchProjectsPaginatedRow struct {
	ID           uuid.UUID       `json:"id"`
	IDUser       uuid.UUID       `json:"id_user"`
	IDCategory   uuid.UUID       `json:"id_category"`
	IsDeployed   bool            `json:"is_deployed"`
	IsMaintained bool            `json:"is_maintained"`
	LiveDemo     sql.NullString  `json:"live_demo"`
	SourceCode   sql.NullString  `json:"source_code"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	User         json.RawMessage `json:"user"`
	Category     json.RawMessage `json:"category"`
	Translations interface{}     `json:"translations"`
	Techs        interface{}     `json:"techs"`
	Images       interface{}     `json:"images"`
}

func (q *Queries) SearchProjectsPaginated(ctx context.Context, arg SearchProjectsPaginatedParams) ([]SearchProjectsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProjectsPaginatedRow{}
	for rows.Next() {
		var i SearchProjectsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDCategory,
			&i.IsDeployed,
			&i.IsMaintained,
			&i.LiveDemo,
			&i.SourceCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.User,
			&i.Category,
			&i.Translations,
			&i.Techs,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET id_category = COALESCE($1, id_category),
  is_deployed = COALESCE($2, is_deployed),
  is_maintained = COALESCE($3, is_maintained),
  live_demo = COALESCE($4, live_demo),
  source_code = COALESCE($5, source_code)
WHERE id = $6
RETURNING id, id_user, id_category, is_deployed, is_maintained, live_demo, source_code, created_at, updated_at
`

type UpdateProjectParams struct {
	IDCategory   uuid.NullUUID  `json:"id_category"`
	IsDeployed   sql.NullBool   `json:"is_deployed"`
	IsMaintained sql.NullBool   `json:"is_maintained"`
	LiveDemo     sql.NullString `json:"live_demo"`
	SourceCode   sql.NullString `json:"source_code"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.IDCategory,
		arg.IsDeployed,
		arg.IsMaintained,
		arg.LiveDemo,
		arg.SourceCode,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDCategory,
		&i.IsDeployed,
		&i.IsMaintained,
		&i.LiveDemo,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
