// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_translations.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const checkProjectTranslationExists = `-- name: CheckProjectTranslationExists :one
SELECT EXISTS (
    SELECT 1
    FROM project_translations
    WHERE id = $1
  ) as exists
`

func (q *Queries) CheckProjectTranslationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectTranslationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProjectTranslations = `-- name: CountProjectTranslations :one
SELECT COUNT(*) as total
FROM project_translations
`

func (q *Queries) CountProjectTranslations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectTranslations)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProjectTranslation = `-- name: CreateProjectTranslation :one
INSERT INTO project_translations (id, id_project, id_language, name, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, id_project, id_language, name, description, created_at, updated_at
`

type CreateProjectTranslationParams struct {
	ID          uuid.UUID      `json:"id"`
	IDProject   uuid.UUID      `json:"id_project"`
	IDLanguage  uuid.UUID      `json:"id_language"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProjectTranslation(ctx context.Context, arg CreateProjectTranslationParams) (ProjectTranslation, error) {
	row := q.db.QueryRowContext(ctx, createProjectTranslation,
		arg.ID,
		arg.IDProject,
		arg.IDLanguage,
		arg.Name,
		arg.Description,
	)
	var i ProjectTranslation
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.IDLanguage,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectTranslationsBatch = `-- name: CreateProjectTranslationsBatch :many
INSERT INTO project_translations (id, id_project, id_language, name, description)
SELECT (item->>'id')::uuid,
  (item->>'id_project')::uuid,
  (item->>'id_language')::uuid,
  item->>'name',
  item->>'description'
FROM json_array_elements($1::json) AS item
RETURNING id, id_project, id_language, name, description, created_at, updated_at
`

func (q *Queries) CreateProjectTranslationsBatch(ctx context.Context, dollar_1 json.RawMessage) ([]ProjectTranslation, error) {
	rows, err := q.db.QueryContext(ctx, createProjectTranslationsBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.IDLanguage,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProjectTranslation = `-- name: DeleteProjectTranslation :exec
DELETE FROM project_translations
WHERE id = $1
`

func (q *Queries) DeleteProjectTranslation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectTranslation, id)
	return err
}

const getProjectTranslation = `-- name: GetProjectTranslation :one
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectTranslation(ctx context.Context, id uuid.UUID) (ProjectTranslation, error) {
	row := q.db.QueryRowContext(ctx, getProjectTranslation, id)
	var i ProjectTranslation
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.IDLanguage,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTranslationByName = `-- name: GetProjectTranslationByName :one
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetProjectTranslationByName(ctx context.Context, name string) (ProjectTranslation, error) {
	row := q.db.QueryRowContext(ctx, getProjectTranslationByName, name)
	var i ProjectTranslation
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.IDLanguage,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTranslationsCursorFirst = `-- name: GetProjectTranslationsCursorFirst :many
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetProjectTranslationsCursorFirst(ctx context.Context, limit int32) ([]ProjectTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getProjectTranslationsCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.IDLanguage,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectTranslationsPaginated = `-- name: GetProjectTranslationsPaginated :many
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetProjectTranslationsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetProjectTranslationsPaginated(ctx context.Context, arg GetProjectTranslationsPaginatedParams) ([]ProjectTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getProjectTranslationsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.IDLanguage,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectTranslations = `-- name: SearchProjectTranslations :many
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
`

func (q *Queries) SearchProjectTranslations(ctx context.Context, dollar_1 sql.NullString) ([]ProjectTranslation, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectTranslations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.IDLanguage,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectTranslationsPaginated = `-- name: SearchProjectTranslationsPaginated :many
SELECT id, id_project, id_language, name, description, created_at, updated_at
FROM project_translations
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProjectTranslationsPaginatedParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchProjectTranslationsPaginated(ctx context.Context, arg SearchProjectTranslationsPaginatedParams) ([]ProjectTranslation, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectTranslationsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTranslation{}
	for rows.Next() {
		var i ProjectTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDProject,
			&i.IDLanguage,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectTranslation = `-- name: UpdateProjectTranslation :one
UPDATE project_translations
SET id_language = COALESCE($2, id_language),
  name = COALESCE($3, name),
  description = COALESCE($4, description)
WHERE id = $1
RETURNING id, id_project, id_language, name, description, created_at, updated_at
`

type UpdateProjectTranslationParams struct {
	ID          uuid.UUID      `json:"id"`
	IDLanguage  uuid.UUID      `json:"id_language"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateProjectTranslation(ctx context.Context, arg UpdateProjectTranslationParams) (ProjectTranslation, error) {
	row := q.db.QueryRowContext(ctx, updateProjectTranslation,
		arg.ID,
		arg.IDLanguage,
		arg.Name,
		arg.Description,
	)
	var i ProjectTranslation
	err := row.Scan(
		&i.ID,
		&i.IDProject,
		&i.IDLanguage,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
