// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckLangCodeExists(ctx context.Context, langCode string) (bool, error)
	CheckLanguageExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckNameExists(ctx context.Context, name string) (bool, error)
	CheckTechExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckTechNameExists(ctx context.Context, name string) (bool, error)
	CheckUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckUserTranslationExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CountLanguages(ctx context.Context) (int64, error)
	CountTechs(ctx context.Context) (int64, error)
	CountUserTranslations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateTech(ctx context.Context, arg CreateTechParams) (Tech, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserTranslation(ctx context.Context, arg CreateUserTranslationParams) (UserTranslation, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteLanguage(ctx context.Context, id uuid.UUID) error
	DeleteTech(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserTranslation(ctx context.Context, id uuid.UUID) error
	GetCategories(ctx context.Context) ([]Category, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetLanguage(ctx context.Context, id uuid.UUID) (Language, error)
	GetLanguageByLangCode(ctx context.Context, langCode string) (Language, error)
	GetLanguageByName(ctx context.Context, name string) (Language, error)
	GetLanguagesCursorFirst(ctx context.Context, limit int32) ([]Language, error)
	GetLanguagesPaginated(ctx context.Context, arg GetLanguagesPaginatedParams) ([]Language, error)
	GetTech(ctx context.Context, id uuid.UUID) (Tech, error)
	GetTechByName(ctx context.Context, name string) (Tech, error)
	GetTechsCursorFirst(ctx context.Context, limit int32) ([]Tech, error)
	GetTechsPaginated(ctx context.Context, arg GetTechsPaginatedParams) ([]Tech, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserTranslation(ctx context.Context, id uuid.UUID) (UserTranslation, error)
	GetUserTranslationByUserIDAndLangCode(ctx context.Context, arg GetUserTranslationByUserIDAndLangCodeParams) (UserTranslation, error)
	GetUserTranslationByUserIDAndLangID(ctx context.Context, arg GetUserTranslationByUserIDAndLangIDParams) (UserTranslation, error)
	GetUserTranslationByUserIDAndLangName(ctx context.Context, arg GetUserTranslationByUserIDAndLangNameParams) (UserTranslation, error)
	GetUserTranslationsByUserIDPaginated(ctx context.Context, arg GetUserTranslationsByUserIDPaginatedParams) ([]UserTranslation, error)
	GetUserTranslationsCursorFirst(ctx context.Context, limit int32) ([]UserTranslation, error)
	GetUserTranslationsPaginated(ctx context.Context, arg GetUserTranslationsPaginatedParams) ([]UserTranslation, error)
	GetUsersCursorFirst(ctx context.Context, limit int32) ([]User, error)
	GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]User, error)
	SearchLanguages(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesByLangCode(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesByName(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesPaginated(ctx context.Context, arg SearchLanguagesPaginatedParams) ([]Language, error)
	SearchTechs(ctx context.Context, dollar_1 sql.NullString) ([]Tech, error)
	SearchTechsPaginated(ctx context.Context, arg SearchTechsPaginatedParams) ([]Tech, error)
	SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByEmail(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByFullName(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByUsername(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error)
	UpdateTech(ctx context.Context, arg UpdateTechParams) (Tech, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserTranslation(ctx context.Context, arg UpdateUserTranslationParams) (UserTranslation, error)
}

var _ Querier = (*Queries)(nil)
