// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckLangCodeExists(ctx context.Context, langCode string) (bool, error)
	CheckLanguageExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckNameExists(ctx context.Context, name string) (bool, error)
	CheckUserExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CountLanguages(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateLanguage(ctx context.Context, arg CreateLanguageParams) (Language, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteLanguage(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetCategories(ctx context.Context) ([]Category, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetLanguage(ctx context.Context, id uuid.UUID) (Language, error)
	GetLanguageByLangCode(ctx context.Context, langCode string) (Language, error)
	GetLanguageByName(ctx context.Context, name string) (Language, error)
	GetLanguagesCursorFirst(ctx context.Context, limit int32) ([]Language, error)
	GetLanguagesPaginated(ctx context.Context, arg GetLanguagesPaginatedParams) ([]Language, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersCursorBackward(ctx context.Context, arg GetUsersCursorBackwardParams) ([]User, error)
	GetUsersCursorFirst(ctx context.Context, limit int32) ([]User, error)
	GetUsersCursorForward(ctx context.Context, arg GetUsersCursorForwardParams) ([]User, error)
	GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]User, error)
	GetUsersPaginatedWithCount(ctx context.Context, arg GetUsersPaginatedWithCountParams) ([]GetUsersPaginatedWithCountRow, error)
	SearchLanguages(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesByLangCode(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesByName(ctx context.Context, dollar_1 sql.NullString) ([]Language, error)
	SearchLanguagesPaginated(ctx context.Context, arg SearchLanguagesPaginatedParams) ([]Language, error)
	SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByEmail(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByFullName(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersByUsername(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (Language, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
