// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tech_stacks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTechStack = `-- name: CreateTechStack :one
INSERT INTO tech_stacks (id_project, id_tech)
VALUES ($1, $2)
RETURNING id_project, id_tech, created_at, updated_at
`

type CreateTechStackParams struct {
	IDProject uuid.UUID `json:"id_project"`
	IDTech    uuid.UUID `json:"id_tech"`
}

func (q *Queries) CreateTechStack(ctx context.Context, arg CreateTechStackParams) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, createTechStack, arg.IDProject, arg.IDTech)
	var i TechStack
	err := row.Scan(
		&i.IDProject,
		&i.IDTech,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTechStack = `-- name: DeleteTechStack :exec
DELETE FROM tech_stacks
WHERE id_project = $1
  AND id_tech = $2
`

type DeleteTechStackParams struct {
	IDProject uuid.UUID `json:"id_project"`
	IDTech    uuid.UUID `json:"id_tech"`
}

func (q *Queries) DeleteTechStack(ctx context.Context, arg DeleteTechStackParams) error {
	_, err := q.db.ExecContext(ctx, deleteTechStack, arg.IDProject, arg.IDTech)
	return err
}

const updateTechStack = `-- name: UpdateTechStack :one
UPDATE tech_stacks
SET id_project = COALESCE($3, id_project),
  id_tech = COALESCE($4, id_tech)
WHERE id_project = $1
  AND id_tech = $2
RETURNING id_project, id_tech, created_at, updated_at
`

type UpdateTechStackParams struct {
	IDProject   uuid.UUID `json:"id_project"`
	IDTech      uuid.UUID `json:"id_tech"`
	IDProject_2 uuid.UUID `json:"id_project_2"`
	IDTech_2    uuid.UUID `json:"id_tech_2"`
}

func (q *Queries) UpdateTechStack(ctx context.Context, arg UpdateTechStackParams) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, updateTechStack,
		arg.IDProject,
		arg.IDTech,
		arg.IDProject_2,
		arg.IDTech_2,
	)
	var i TechStack
	err := row.Scan(
		&i.IDProject,
		&i.IDTech,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
