// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: techs.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkTechExists = `-- name: CheckTechExists :one
SELECT EXISTS (
    SELECT 1
    FROM techs
    WHERE id = $1
  ) as exists
`

func (q *Queries) CheckTechExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkTechExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkTechNameExists = `-- name: CheckTechNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM techs
    WHERE name = $1
  ) as exists
`

func (q *Queries) CheckTechNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkTechNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countTechs = `-- name: CountTechs :one
SELECT COUNT(*) as total
FROM techs
`

func (q *Queries) CountTechs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTechs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createTech = `-- name: CreateTech :one
INSERT INTO techs (id, name, description, logo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, logo_url, created_at, updated_at
`

type CreateTechParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LogoUrl     sql.NullString `json:"logo_url"`
}

func (q *Queries) CreateTech(ctx context.Context, arg CreateTechParams) (Tech, error) {
	row := q.db.QueryRowContext(ctx, createTech,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
	)
	var i Tech
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTech = `-- name: DeleteTech :exec
DELETE FROM techs
WHERE id = $1
`

func (q *Queries) DeleteTech(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTech, id)
	return err
}

const getTech = `-- name: GetTech :one
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTech(ctx context.Context, id uuid.UUID) (Tech, error) {
	row := q.db.QueryRowContext(ctx, getTech, id)
	var i Tech
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechByName = `-- name: GetTechByName :one
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetTechByName(ctx context.Context, name string) (Tech, error) {
	row := q.db.QueryRowContext(ctx, getTechByName, name)
	var i Tech
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechsCursorFirst = `-- name: GetTechsCursorFirst :many
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetTechsCursorFirst(ctx context.Context, limit int32) ([]Tech, error) {
	rows, err := q.db.QueryContext(ctx, getTechsCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tech{}
	for rows.Next() {
		var i Tech
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechsPaginated = `-- name: GetTechsPaginated :many
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetTechsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetTechsPaginated(ctx context.Context, arg GetTechsPaginatedParams) ([]Tech, error) {
	rows, err := q.db.QueryContext(ctx, getTechsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tech{}
	for rows.Next() {
		var i Tech
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTechs = `-- name: SearchTechs :many
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
`

func (q *Queries) SearchTechs(ctx context.Context, dollar_1 sql.NullString) ([]Tech, error) {
	rows, err := q.db.QueryContext(ctx, searchTechs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tech{}
	for rows.Next() {
		var i Tech
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTechsPaginated = `-- name: SearchTechsPaginated :many
SELECT id, name, description, logo_url, created_at, updated_at
FROM techs
WHERE name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  created_at DESC
LIMIT $2 OFFSET $3
`

type SearchTechsPaginatedParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchTechsPaginated(ctx context.Context, arg SearchTechsPaginatedParams) ([]Tech, error) {
	rows, err := q.db.QueryContext(ctx, searchTechsPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tech{}
	for rows.Next() {
		var i Tech
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTech = `-- name: UpdateTech :one
UPDATE techs
SET name = COALESCE($2, name),
  description = COALESCE($3, description),
  logo_url = COALESCE($4, logo_url)
WHERE id = $1
RETURNING id, name, description, logo_url, created_at, updated_at
`

type UpdateTechParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	LogoUrl     sql.NullString `json:"logo_url"`
}

func (q *Queries) UpdateTech(ctx context.Context, arg UpdateTechParams) (Tech, error) {
	row := q.db.QueryRowContext(ctx, updateTech,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
	)
	var i Tech
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
