// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
  ) as exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
  ) as exists
`

func (q *Queries) CheckUserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username = $1
  ) as exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) as total
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    username,
    email,
    password,
    role,
    address,
    full_name
  )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, password, role, address, full_name, id_language, created_at, updated_at
`

type CreateUserParams struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Role     UserRole       `json:"role"`
	Address  sql.NullString `json:"address"`
	FullName sql.NullString `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.Address,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersCursorFirst = `-- name: GetUsersCursorFirst :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetUsersCursorFirst(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersPaginated = `-- name: GetUsersPaginated :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsersPaginated(ctx context.Context, arg GetUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE (
    username ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR full_name ILIKE '%' || $1 || '%'
  )
ORDER BY CASE
    WHEN username ILIKE $1 || '%' THEN 1
    WHEN email ILIKE $1 || '%' THEN 2
    WHEN full_name ILIKE $1 || '%' THEN 3
    ELSE 4
  END,
  created_at DESC
`

func (q *Queries) SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE email ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN email ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  email ASC
`

func (q *Queries) SearchUsersByEmail(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByEmail, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByFullName = `-- name: SearchUsersByFullName :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE full_name ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN full_name ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  full_name ASC
`

func (q *Queries) SearchUsersByFullName(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByFullName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE username ILIKE '%' || $1 || '%'
ORDER BY CASE
    WHEN username ILIKE $1 || '%' THEN 1
    ELSE 2
  END,
  username ASC
`

func (q *Queries) SearchUsersByUsername(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByUsername, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersPaginated = `-- name: SearchUsersPaginated :many
SELECT id, username, email, password, role, address, full_name, id_language, created_at, updated_at
FROM users
WHERE (
    username ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
    OR full_name ILIKE '%' || $1 || '%'
  )
ORDER BY CASE
    WHEN username ILIKE $1 || '%' THEN 1
    WHEN email ILIKE $1 || '%' THEN 2
    WHEN full_name ILIKE $1 || '%' THEN 3
    ELSE 4
  END,
  created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersPaginatedParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersPaginated, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.Address,
			&i.FullName,
			&i.IDLanguage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE($2, username),
  email = COALESCE($3, email),
  password = COALESCE($4, password),
  role = COALESCE($5, role),
  address = COALESCE($6, address),
  full_name = COALESCE($7, full_name)
WHERE id = $1
RETURNING id, username, email, password, role, address, full_name, id_language, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Role     UserRole       `json:"role"`
	Address  sql.NullString `json:"address"`
	FullName sql.NullString `json:"full_name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.Address,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET address = COALESCE($2, address),
  full_name = COALESCE($3, full_name)
WHERE id = $1
RETURNING id, username, email, password, role, address, full_name, id_language, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID      `json:"id"`
	Address  sql.NullString `json:"address"`
	FullName sql.NullString `json:"full_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.ID, arg.Address, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Address,
		&i.FullName,
		&i.IDLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
