// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_translations.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const checkUserTranslationExists = `-- name: CheckUserTranslationExists :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      user_translations
    WHERE
      id = $1
  ) as exists
`

func (q *Queries) CheckUserTranslationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserTranslationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserTranslations = `-- name: CountUserTranslations :one
SELECT
  COUNT(*) as total
FROM
  user_translations
`

func (q *Queries) CountUserTranslations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserTranslations)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUserTranslation = `-- name: CreateUserTranslation :one
INSERT INTO
  user_translations (
    id,
    id_user,
    id_language,
    bio,
    about_me,
    additional_skills,
    languages,
    quote
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
`

type CreateUserTranslationParams struct {
	ID               uuid.UUID      `json:"id"`
	IDUser           uuid.UUID      `json:"id_user"`
	IDLanguage       uuid.UUID      `json:"id_language"`
	Bio              sql.NullString `json:"bio"`
	AboutMe          sql.NullString `json:"about_me"`
	AdditionalSkills []string       `json:"additional_skills"`
	Languages        []string       `json:"languages"`
	Quote            sql.NullString `json:"quote"`
}

func (q *Queries) CreateUserTranslation(ctx context.Context, arg CreateUserTranslationParams) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, createUserTranslation,
		arg.ID,
		arg.IDUser,
		arg.IDLanguage,
		arg.Bio,
		arg.AboutMe,
		pq.Array(arg.AdditionalSkills),
		pq.Array(arg.Languages),
		arg.Quote,
	)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserTranslation = `-- name: DeleteUserTranslation :exec
DELETE FROM user_translations
WHERE
  id = $1
`

func (q *Queries) DeleteUserTranslation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserTranslation, id)
	return err
}

const getUserTranslation = `-- name: GetUserTranslation :one
SELECT
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
FROM
  user_translations
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetUserTranslation(ctx context.Context, id uuid.UUID) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, getUserTranslation, id)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTranslationByUserIDAndLangCode = `-- name: GetUserTranslationByUserIDAndLangCode :one
SELECT
  ut.id, ut.id_user, ut.id_language, ut.bio, ut.about_me, ut.additional_skills, ut.languages, ut.quote, ut.created_at, ut.updated_at
FROM
  user_translations ut
  JOIN languages l ON ut.id_language = l.id
WHERE
  ut.id_user = $1
  AND l.lang_code = $2
LIMIT
  1
`

type GetUserTranslationByUserIDAndLangCodeParams struct {
	IDUser   uuid.UUID `json:"id_user"`
	LangCode string    `json:"lang_code"`
}

func (q *Queries) GetUserTranslationByUserIDAndLangCode(ctx context.Context, arg GetUserTranslationByUserIDAndLangCodeParams) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, getUserTranslationByUserIDAndLangCode, arg.IDUser, arg.LangCode)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTranslationByUserIDAndLangID = `-- name: GetUserTranslationByUserIDAndLangID :one
SELECT
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
FROM
  user_translations
WHERE
  id_user = $1
  AND id_language = $2
LIMIT
  1
`

type GetUserTranslationByUserIDAndLangIDParams struct {
	IDUser     uuid.UUID `json:"id_user"`
	IDLanguage uuid.UUID `json:"id_language"`
}

func (q *Queries) GetUserTranslationByUserIDAndLangID(ctx context.Context, arg GetUserTranslationByUserIDAndLangIDParams) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, getUserTranslationByUserIDAndLangID, arg.IDUser, arg.IDLanguage)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTranslationByUserIDAndLangName = `-- name: GetUserTranslationByUserIDAndLangName :one
SELECT
  ut.id, ut.id_user, ut.id_language, ut.bio, ut.about_me, ut.additional_skills, ut.languages, ut.quote, ut.created_at, ut.updated_at
FROM
  user_translations ut
  JOIN languages l ON ut.id_language = l.id
WHERE
  ut.id_user = $1
  AND l.name = $2
LIMIT
  1
`

type GetUserTranslationByUserIDAndLangNameParams struct {
	IDUser uuid.UUID `json:"id_user"`
	Name   string    `json:"name"`
}

func (q *Queries) GetUserTranslationByUserIDAndLangName(ctx context.Context, arg GetUserTranslationByUserIDAndLangNameParams) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, getUserTranslationByUserIDAndLangName, arg.IDUser, arg.Name)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTranslationsByUserIDPaginated = `-- name: GetUserTranslationsByUserIDPaginated :many
SELECT
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
FROM
  user_translations
WHERE
  id_user = $1
ORDER BY
  created_at DESC
LIMIT
  $2
OFFSET
  $3
`

type GetUserTranslationsByUserIDPaginatedParams struct {
	IDUser uuid.UUID `json:"id_user"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserTranslationsByUserIDPaginated(ctx context.Context, arg GetUserTranslationsByUserIDPaginatedParams) ([]UserTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getUserTranslationsByUserIDPaginated, arg.IDUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTranslation{}
	for rows.Next() {
		var i UserTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDLanguage,
			&i.Bio,
			&i.AboutMe,
			pq.Array(&i.AdditionalSkills),
			pq.Array(&i.Languages),
			&i.Quote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTranslationsCursorFirst = `-- name: GetUserTranslationsCursorFirst :many
SELECT
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
FROM
  user_translations
ORDER BY
  created_at DESC
LIMIT
  $1
`

func (q *Queries) GetUserTranslationsCursorFirst(ctx context.Context, limit int32) ([]UserTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getUserTranslationsCursorFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTranslation{}
	for rows.Next() {
		var i UserTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDLanguage,
			&i.Bio,
			&i.AboutMe,
			pq.Array(&i.AdditionalSkills),
			pq.Array(&i.Languages),
			&i.Quote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTranslationsPaginated = `-- name: GetUserTranslationsPaginated :many
SELECT
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
FROM
  user_translations
ORDER BY
  created_at DESC
LIMIT
  $1
OFFSET
  $2
`

type GetUserTranslationsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUserTranslationsPaginated(ctx context.Context, arg GetUserTranslationsPaginatedParams) ([]UserTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getUserTranslationsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTranslation{}
	for rows.Next() {
		var i UserTranslation
		if err := rows.Scan(
			&i.ID,
			&i.IDUser,
			&i.IDLanguage,
			&i.Bio,
			&i.AboutMe,
			pq.Array(&i.AdditionalSkills),
			pq.Array(&i.Languages),
			&i.Quote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTranslation = `-- name: UpdateUserTranslation :one
UPDATE user_translations
SET
  id_user = COALESCE($2, id_user),
  id_language = COALESCE($3, id_language),
  bio = COALESCE($4, bio),
  about_me = COALESCE($5, about_me),
  additional_skills = COALESCE($6, additional_skills),
  languages = COALESCE($7, languages),
  quote = COALESCE($8, quote)
WHERE
  id = $1
RETURNING
  id, id_user, id_language, bio, about_me, additional_skills, languages, quote, created_at, updated_at
`

type UpdateUserTranslationParams struct {
	ID               uuid.UUID      `json:"id"`
	IDUser           uuid.UUID      `json:"id_user"`
	IDLanguage       uuid.UUID      `json:"id_language"`
	Bio              sql.NullString `json:"bio"`
	AboutMe          sql.NullString `json:"about_me"`
	AdditionalSkills []string       `json:"additional_skills"`
	Languages        []string       `json:"languages"`
	Quote            sql.NullString `json:"quote"`
}

func (q *Queries) UpdateUserTranslation(ctx context.Context, arg UpdateUserTranslationParams) (UserTranslation, error) {
	row := q.db.QueryRowContext(ctx, updateUserTranslation,
		arg.ID,
		arg.IDUser,
		arg.IDLanguage,
		arg.Bio,
		arg.AboutMe,
		pq.Array(arg.AdditionalSkills),
		pq.Array(arg.Languages),
		arg.Quote,
	)
	var i UserTranslation
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDLanguage,
		&i.Bio,
		&i.AboutMe,
		pq.Array(&i.AdditionalSkills),
		pq.Array(&i.Languages),
		&i.Quote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
